markdown: rdiscount
pygments: true
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://ruby-gettext.github.io
gettext_version: 3.0.5
gettext_release_date: 2014-02-02
locale_version: 2.1.0
locale_release_date: 2012-12-15
