markdown: kramdown
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://ruby-gettext.github.io
gettext_version: 3.1.5
gettext_release_date: 2015-01-17
locale_version: 2.1.0
locale_release_date: 2012-12-15

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
