markdown: rdiscount
pygments: true
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://ruby-gettext.github.com
gettext_version: 3.0.3
gettext_release_date: 2013-12-15
locale_version: 2.1.0
locale_release_date: 2012-12-15
