markdown: rdiscount
pygments: true
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://ruby-gettext.github.com
gettext_version: 2.3.0
gettext_release_date: 2012-08-29
locale_version: 2.0.8
locale_release_date: 2012-08-29
